apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  namespace: backend
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - name: main
        image: docker.io/vianagallery/gallery-api:alp-0.0.5
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
        env:
        - name: TEST_NAME
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: TEST_NAME
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: POSTGRES_URL
        - name: ADMIN_JWT
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: ADMIN_JWT
        - name: AZURE_STORAGE_CNN_STR
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: AZURE_STORAGE_CNN_STR
      imagePullSecrets:
      - name: docker-hub-cred
---
apiVersion: v1
kind: Service
metadata:
  name: gallery
  namespace: backend
  labels:
    app: gallery
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    # protocol: TCP
  selector:
    app: gallery
    # internalTrafficPolicy: Cluster
    # ipFamilies:
    # - IPv4
    # ipFamilyPolicy: SingleStack
    # sessionAffinity: None
    # type: LoadBalancer
# status:
#   loadBalancer: {}
