apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  namespace: backend
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - name: backend
        image: docker.io/vianagallery/gallery-api:alp-0.0.3
        imagePullPolicy: Always
        # resources:
          # limits:
          #   memory: 512Mi
          #   cpu: "1"
          # requests:
          #   memory: 256Mi
          #   cpu: "0.2"
        ports:
        - containerPort: 8080
        # - name: http
        env:
        - name: TEST_NAME
          value: "K8S-WORKING-02"
        - name: POSTGRES_URL
          value: "postgresql+psycopg2://postgres:example@postgres:5432/database"
        - name: ADMIN_JWT
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXJjZWxvQGVtYWlsLmNvbSIsImV4cCI6MTcwMzQ1MTc2NH0.7H0tsroOtGhRmoixujPCqOb5w7fIB8YjTRkEnN88XCI"
        - name: AZURE_STORAGE_CNN_STR
          value: "DefaultEndpointsProtocol=https;AccountName=01vianadev;AccountKey=Rv3sdophD7yqxfpuVdDdeyEANR0XJ9EpRRfjTn+pcjz4mPqbiYQRzeNdOJIPhyc8U5CWPXktvVNL+AStoT9SlA==;EndpointSuffix=core.windows.net"
      imagePullSecrets:
      - name: docker-hub-cred
---
apiVersion: v1
kind: Service
metadata:
  name: gallery
  namespace: backend
  labels:
    app: gallery
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    # protocol: TCP
  selector:
    app: gallery
  # internalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  # sessionAffinity: None
  # type: LoadBalancer
# status:
#   loadBalancer: {}