apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gallery
  namespace: backend
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev.api.dreampuppy.com.br
    secretName: letsencrypt-nginx
  rules:
    - host: dev.api.dreampuppy.com.br
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gallery
              port:
                number: 80
