apiVersion: v1
kind: Secret
metadata:
  name: gallery-secret
  namespace: backend
type: Opaque
# echo -n "$value" | base64
data:
  POSTGRES_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOmNHOXpkR2R5WlhOeGJDdHdjM2xqYjNCbk1qb3ZMM0J2YzNSbmNtVnpPbVY0WVcxd2JHVkFjRzl6ZEdkeVpYTTZOVFF6TWk5a1lYUmhZbUZ6WlFAcG9zdGdyZXM6NTQzMi9kYXRhYmFzZQ==
  # ! Security Warning !
  ADMIN_JWT: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lKdFlYSmpaV3h2UUdWdFlXbHNMbU52YlNJc0ltVjRjQ0k2TVRjd016UTFNVGMyTkgwLjdIMHRzcm9PdEdoUm1vaXh1alBDcU9iNXc3ZklCOFlqVFJrRW5OODhYQ0k=
  CFI_ID: Mzk2YTFmZDA1Njg5YzQ1ZjA3YmRkMTkxNzA1ZTk4ZGQ=
  CFI_TOKEN: YWNhLTBKR2VRZmdxY3NlRjF6RGM1WVNWZjYzTXAwWHMyY090THYtSg==
