apiVersion: v1
kind: Secret
metadata:
  name: gallery-secret
  namespace: backend
type: Opaque
# echo -n "$value" | base64
data:
  TEST_NAME: SzhTLVdPUktJTkctMDM=
  POSTGRES_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Bvc3RncmVzOmV4YW1wbGVAcG9zdGdyZXM6NTQzMi9kYXRhYmFzZQ==
  ADMIN_JWT: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lKdFlYSmpaV3h2UUdWdFlXbHNMbU52YlNJc0ltVjRjQ0k2TVRjd016UTFNVGMyTkgwLjdIMHRzcm9PdEdoUm1vaXh1alBDcU9iNXc3ZklCOFlqVFJrRW5OODhYQ0k=
  AZURE_STORAGE_CNN_STR: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPTAxdmlhbmFkZXY7QWNjb3VudEtleT1SdjNzZG9waEQ3eXF4ZnB1VmREZGV5RUFOUjBYSjlFcFJSZmpUbitwY2p6NG1QcWJpWVFSemVOZE9KSVBoeWM4VTVDV1BYa3R2Vk5MK0FTdG9UOVNsQT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
