apiVersion: v1
kind: Service
metadata:
  name: gallery
  namespace: default
  labels:
    app: gallery
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: name-of-service-port-t01
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: gallery
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
