apiVersion: v1
kind: Service
metadata:
  name: gallery
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 443
    targetPort: http-web-svc