apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - name: gallery-container-t01
        image: vianagallery/gallery-api:latest
        ports:
        - containerPort: 80
        env:
        - name: TEST_NAME
          value: "K8S-WORKING"
        - name: POSTGRES_URL
          value: "postgresql+psycopg2://postgres:example@postgres:5432/database"
        - name: ADMIN_JWT
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXJjZWxvQGVtYWlsLmNvbSIsImV4cCI6MTcwMzQ1MTc2NH0.7H0tsroOtGhRmoixujPCqOb5w7fIB8YjTRkEnN88XCI"
        - name: AZURE_STORAGE_CNN_STR
          value: "DefaultEndpointsProtocol=https;AccountName=01vianadev;AccountKey=Rv3sdophD7yqxfpuVdDdeyEANR0XJ9EpRRfjTn+pcjz4mPqbiYQRzeNdOJIPhyc8U5CWPXktvVNL+AStoT9SlA==;EndpointSuffix=core.windows.net"
      imagePullSecrets:
      - name: regcred
