apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
      containers:
      - name: main
        image: postgres:latest
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: database
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: example

