apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
  namespace: backend
  labels:
    app: gallery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - name: main
        image: docker.io/vianagallery/gallery-api:stable
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
        env:
        - name: TEST_NAME
          value: Cluster Prod
        - name: API_VERSION
          value: 1.0.0
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: POSTGRES_URL
        - name: ADMIN_JWT
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: ADMIN_JWT
        # CloudFlareImages Account Id
        - name: CFI_ID
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: CFI_ID
        - name: CFI_TOKEN
          valueFrom:
            secretKeyRef:
              name: gallery-secret
              key: CFI_TOKEN
      imagePullSecrets:
      - name: docker-hub-cred