
apiVersion: v1
kind: Service
metadata:
  name: gallery
  namespace: backend
  labels:
    app: gallery
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    # protocol: TCP
  selector:
    app: gallery
    # internalTrafficPolicy: Cluster
    # ipFamilies:
    # - IPv4
    # ipFamilyPolicy: SingleStack
    # sessionAffinity: None
    # type: LoadBalancer
# status:
#   loadBalancer: {}
