apiVersion: k3d.io/v1alpha3
kind: Simple
name: test
servers: 1
agents: 2
registries:
  create: 
    name: myregistry
  config: |
    configs:
      docker.io:
        auth:
          username: vianagallery
          password: dckr_pat_5eGuYnTjta7PWebXtmh5wjwl450
